apiVersion: v1
kind: ConfigMap
metadata:
  name: player-configmap
data:
  config.json: |
    {
      "server": {
        "debug": true,
        "http_debug": false,
        "http_demo": true,
        "http_dir": "web",
        "http_login": "demo",
        "http_password": "demo",
        "http_port": ":8083",
        "https": false,
        "https_auto_tls": false,
        "https_auto_tls_name": "",
        "https_cert": "server.crt",
        "https_key": "server.key",
        "https_port": ":443",
        "ice_servers": ["stun:stun.l.google.com:19302"],
        "log_level": "debug",
        "rtsp_port": ":5541",
        "token": {
          "backend": "http://127.0.0.1/test.php"
        },
        "defaults": {
          "audio": true
        }
      },
      "streams": {
        "Input": {
          "channels": {
            "cam1": {
              "url": "rtsp://rtsp-source:8554/cam1",
              "debug": false,
              "audio": true,
              "on_demand": true
            }
          },
          "name": "Input"
        },
        "Output": {
          "channels": {
            "inf1": {
              "url": "rtsp://rtsp-out:8554/inf1",
              "debug": false,
              "audio": true,
              "on_demand": true
            }
          },
          "name": "Output"
        }
      }
    }
  